---
- name: Automated Web Server Setup
  hosts: web_servers
  become: yes

  tasks:
    - name: Update package cache (Ubuntu/Debian)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Update packages (CentOS/RHEL)
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install Nginx on Debian/Ubuntu
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Apache on CentOS/RHEL
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Ensure Nginx service is running
      systemd:
        name: nginx
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Ensure Apache service is running
      systemd:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Deploy static HTML page (Debian)
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
      when: ansible_os_family == "Debian"

    - name: Deploy static HTML page (RedHat)
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
        owner: apache
        group: apache
        mode: '0644'
      when: ansible_os_family == "RedHat"

